spring:
  cloud:
    stream:
      function:
        definition: sampleConsumer
      kafka:
        binder:
          brokers:
            - localhost
          auto-create-topics: false
      bindings:
        sampleConsumer-in-0:
          destination: sample-topic
      instance-count: 1
