spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost
          auto-create-topics: false
      binders:
        output:
          destination: sample-topic
          content-type: application/json
          producter:
            partition-count: 1

